# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: winter.forum::lang.channels.reorder_title

# Attribute name
nameFrom: title

# Model Class name
modelClass: Winter\Forum\Models\Channel

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
